// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/dummy/v1/dummy.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DummyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DummyMessage) Reset() {
	*x = DummyMessage{}
	mi := &file_proto_dummy_v1_dummy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DummyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DummyMessage) ProtoMessage() {}

func (x *DummyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dummy_v1_dummy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DummyMessage.ProtoReflect.Descriptor instead.
func (*DummyMessage) Descriptor() ([]byte, []int) {
	return file_proto_dummy_v1_dummy_proto_rawDescGZIP(), []int{0}
}

var File_proto_dummy_v1_dummy_proto protoreflect.FileDescriptor

const file_proto_dummy_v1_dummy_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/dummy/v1/dummy.proto\"\x0e\n" +
	"\fDummyMessage2\x0e\n" +
	"\fDummyServiceB+B\n" +
	"DummyProtoP\x01Z\x1bgo_grpc_proj/proto/dummy/v1b\x06proto3"

var (
	file_proto_dummy_v1_dummy_proto_rawDescOnce sync.Once
	file_proto_dummy_v1_dummy_proto_rawDescData []byte
)

func file_proto_dummy_v1_dummy_proto_rawDescGZIP() []byte {
	file_proto_dummy_v1_dummy_proto_rawDescOnce.Do(func() {
		file_proto_dummy_v1_dummy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dummy_v1_dummy_proto_rawDesc), len(file_proto_dummy_v1_dummy_proto_rawDesc)))
	})
	return file_proto_dummy_v1_dummy_proto_rawDescData
}

var file_proto_dummy_v1_dummy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_dummy_v1_dummy_proto_goTypes = []any{
	(*DummyMessage)(nil), // 0: DummyMessage
}
var file_proto_dummy_v1_dummy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_dummy_v1_dummy_proto_init() }
func file_proto_dummy_v1_dummy_proto_init() {
	if File_proto_dummy_v1_dummy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dummy_v1_dummy_proto_rawDesc), len(file_proto_dummy_v1_dummy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dummy_v1_dummy_proto_goTypes,
		DependencyIndexes: file_proto_dummy_v1_dummy_proto_depIdxs,
		MessageInfos:      file_proto_dummy_v1_dummy_proto_msgTypes,
	}.Build()
	File_proto_dummy_v1_dummy_proto = out.File
	file_proto_dummy_v1_dummy_proto_goTypes = nil
	file_proto_dummy_v1_dummy_proto_depIdxs = nil
}
